allowBuilds:
  esbuild: true
  sharp: true
  supabase: true
  unrs-resolver: true
onlyBuiltDependencies:
  - supabase
publicHoistPattern:
  - '@next/eslint-plugin-next'
  - 'eslint-plugin-react-hooks'
